{% set name = "equilibrator-pathway" %}
{% set version = "0.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-pathway-{{ version }}.tar.gz
  sha256: 9ad1e0ebcae3c15090b65ac553eb02d42cadbc0789aaebbcc90cfd291442d6e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cvxpy ~=1.2
    - equilibrator-api ~=0.4.7
    - numpy ~=1.23
    - osqp ~=0.6
    - pint ~=0.19
    - python >=3.8
    - sbtab ~=1.0
    - scipy ~=1.9
    - seaborn ~=0.12
    - uncertainties ~=3.1

test:
  imports:
    - equilibrator_pathway
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/equilibrator-pathway
  summary: Pathway analysis tools by eQuilibrator
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool for pathway analysis based on Max-min Driving Force, or Enzyme Cost Minimization. These analyses are also available via a web interface at eQuilibrator (http://equilibrator.weizmann.ac.il/pathway).
  dev_url: https://gitlab.com/equilibrator/equilibrator-pathway

extra:
  recipe-maintainers:
    - eladnoor
