{% set name = "equilibrator-pathway" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/equilibrator-pathway-{{ version }}.tar.gz
  sha256: 827b83ac78e548dace8df5d02583240f4f0fe24a44b86e62a4d503724f7f2cda

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41
    - setuptools-scm
    - wheel
    - setuptools-git-versioning >=2.0,<3
    - pip
  run:
    - python >={{ python_min }}
    - pybind11 ~=2.11
    - seaborn-base ~=0.13
    - cvxpy ~=1.5
    - sbtab ~=1.0,>=1.0.8
    - matplotlib-base ~=3.8
    - equilibrator-api ~=0.6.0
    - equilibrator-cache ~=0.6.1

test:
  imports:
    - equilibrator_pathway
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/equilibrator/equilibrator-pathway
  summary: Pathway analysis tools by eQuilibrator
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool for pathway analysis based on Max-min Driving Force, or Enzyme Cost Minimization. These analyses are also available via a web interface at eQuilibrator (http://equilibrator.weizmann.ac.il/pathway).
  dev_url: https://gitlab.com/equilibrator/equilibrator-pathway

extra:
  recipe-maintainers:
    - eladnoor
